### ISSUE TITLE
How many points should coreporters gain?

### ISSUE THREAD

**Issue by nickkolok** [IPTnet/ipt_connect#108]
We have a list of points gained by each member of a team: https://connect.iptnet.info/IPT2018/teams/Ukraine/
![изображение](https://user-images.githubusercontent.com/5008131/55114786-f2a9cc80-50f3-11e9-85d9-5c32132dad82.png)
If a participant is reporting solely, he/she gets all the points. But how should we divide scores for coreporters? As for now, the second reporter gets nothing :(

**Comment by Sebastian-Fava** [comment]
co-reporter is now limited to the presentation stage only, so he/she should get no points imho.
For fairness, the total number of assigned points should be fixed (we give prizes as "best reporter"), and splitting them between reporter and co-reporter doesn't sound very appealing to me

**Comment by lysenko-nikolay** [comment]
There must be the main reporter, who grabs the points, and co-reporter, who helps main to declare a speech during presentation time.
The co-reporter, I think, gain nothing...

**Comment by nickkolok** [comment]
At IPT2018, I took the stage only once, as the second reporter. Since ipt-connect had no coreporter support, that fact wasn't fixed anywhere.

 I wasn't very happy to see that I gathered 0.00 points, i.e. I did nothing!(

**Comment by nickkolok** [comment]
The obvious simple solution: the appropriate coefficient in `parameters.py` (with the possibility to override through Site Configuration, see #189.
